services:
  - type: web
    name: moneymanagement-mm
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./mmi.db
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: LINE_CHANNEL_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
